import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

from setuptools import setup
from setuptools.command.build_ext import build_ext
from setuptools.command.build_py import build_py
from setuptools.extension import Extension

SOURCE_ROOT = Path(__file__).resolve().parent
FRIDA_EXTENSION = os.environ.get("FRIDA_EXTENSION")
FRIDA_CORE_DEVKIT = os.environ.get("FRIDA_CORE_DEVKIT")
FRIDA_GIR_DIR = os.environ.get("FRIDA_GIR_DIR")

GENERATED_PACKAGE_FILES = ["__init__.py", "aio.py", "_frida.pyi"]
SYSTEM_GIR_FILES = ["GLib-2.0.gir", "GObject-2.0.gir", "Gio-2.0.gir"]


def detect_version():
    pkg_info = SOURCE_ROOT / "PKG-INFO"
    if pkg_info.exists():
        version_line = next(
            line
            for line in pkg_info.read_text(encoding="utf-8").splitlines()
            if line.startswith("Version: ")
        )
        return version_line[9:]
    return os.environ.get("FRIDA_VERSION", "0.0.0")


def compute_long_description():
    return (SOURCE_ROOT / "README.md").read_text(encoding="utf-8")


def find_devkit_gir(devkit_dir):
    for name in ("frida-core.gir", "Frida-1.0.gir"):
        path = devkit_dir / name
        if path.is_file():
            return path
    raise RuntimeError(f"Frida devkit at {devkit_dir} does not contain frida-core.gir or Frida-1.0.gir")


def find_system_gir_dir():
    candidates = []
    if FRIDA_GIR_DIR:
        candidates.extend(Path(entry) for entry in FRIDA_GIR_DIR.split(os.pathsep) if entry)
    candidates.extend(
        [
            Path(sys.prefix) / "share" / "gir-1.0",
            Path(sys.base_prefix) / "share" / "gir-1.0",
            Path("/usr/share/gir-1.0"),
        ]
    )

    for directory in candidates:
        if all((directory / name).is_file() for name in SYSTEM_GIR_FILES):
            return directory

    expected = ", ".join(SYSTEM_GIR_FILES)
    raise RuntimeError(
        f"Unable to find {expected}. Install GObject introspection data or set "
        "FRIDA_GIR_DIR to its gir-1.0 directory."
    )


def generated_paths(directory):
    return {
        "py": directory / "__init__.py",
        "pyi": directory / "_frida.pyi",
        "aio": directory / "aio.py",
        "c": directory / "extension.c",
    }


def copy_generated_package(destination, generated):
    destination.mkdir(parents=True, exist_ok=True)
    for name in GENERATED_PACKAGE_FILES:
        shutil.copy2(generated / name, destination / name)


class FridaGeneratedBuildPy(build_py):
    """The public Python package is generated by build_ext from the devkit GIR."""

    def find_package_modules(self, package, package_dir):
        if package == "frida":
            return []
        return super().find_package_modules(package, package_dir)


class FridaPrebuiltExt(build_ext):
    def build_extension(self, ext):
        source = Path(FRIDA_EXTENSION)
        generated = source.parent
        target = Path(self.get_ext_fullpath(ext.name))
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        copy_generated_package(target.parent, generated)


class FridaDevkitExt(build_ext):
    def build_extension(self, ext):
        devkit_dir = Path(FRIDA_CORE_DEVKIT).resolve()
        if not (devkit_dir / "frida-core.h").is_file():
            raise RuntimeError(f"Frida devkit at {devkit_dir} does not contain frida-core.h")

        generator_dir = SOURCE_ROOT / "frida" / "frida_bindgen"
        core_dir = SOURCE_ROOT / "frida" / "frida_bindgen_core"
        if not generator_dir.is_dir() or not core_dir.is_dir():
            raise RuntimeError("The bundled Frida binding generator is incomplete; re-checkout this source tree.")

        gir_dir = find_system_gir_dir()
        output_dir = Path(self.build_temp) / "frida-bindgen"
        output_dir.mkdir(parents=True, exist_ok=True)
        outputs = generated_paths(output_dir)

        env = os.environ.copy()
        source_path = str(SOURCE_ROOT / "frida")
        env["PYTHONPATH"] = source_path + (
            os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else ""
        )
        subprocess.run(
            [
                sys.executable,
                "-m",
                "frida_bindgen",
                f"--frida-gir={find_devkit_gir(devkit_dir)}",
                f"--frida-header={devkit_dir / 'frida-core.h'}",
                f"--glib-gir={gir_dir / 'GLib-2.0.gir'}",
                f"--gobject-gir={gir_dir / 'GObject-2.0.gir'}",
                f"--gio-gir={gir_dir / 'Gio-2.0.gir'}",
                f"--output-py={outputs['py']}",
                f"--output-pyi={outputs['pyi']}",
                f"--output-aio={outputs['aio']}",
                f"--output-c={outputs['c']}",
            ],
            cwd=SOURCE_ROOT,
            env=env,
            check=True,
        )

        ext.sources = [str(outputs["c"])]
        ext.include_dirs = [str(devkit_dir)]
        ext.library_dirs = [str(devkit_dir)]
        ext.libraries = ["frida-core"]
        ext.extra_link_args = extra_link_args()
        super().build_extension(ext)

        copy_generated_package(Path(self.get_ext_fullpath(ext.name)).parent, output_dir)


class FridaMissingDevkitBuildExt(build_ext):
    def build_extension(self, ext):
        raise RuntimeError(
            "Need FRIDA_CORE_DEVKIT to build from source. Download a frida-core devkit from "
            "https://github.com/frida/frida/releases and point FRIDA_CORE_DEVKIT at it."
        )


def extra_link_args():
    system = platform.system()
    if system == "Windows":
        return []
    if system == "Darwin":
        if "_PYTHON_HOST_PLATFORM" not in os.environ:
            if platform.machine() == "arm64":
                host_arch = "arm64"
                macos_req = "11.0"
            else:
                host_arch = "x86_64"
                macos_req = "10.9"
            os.environ["_PYTHON_HOST_PLATFORM"] = f"macosx-{macos_req}-{host_arch}"
            os.environ["ARCHFLAGS"] = f"-arch {host_arch}"
            os.environ["MACOSX_DEPLOYMENT_TARGET"] = macos_req
        return ["-Wl,-exported_symbol,_PyInit__frida", "-Wl,-dead_strip"]
    return [
        f"-Wl,--version-script,{SOURCE_ROOT / 'frida' / 'extension.version'}",
        "-Wl,--gc-sections",
    ]


def select_build_ext():
    if FRIDA_EXTENSION is not None:
        return FridaPrebuiltExt
    if FRIDA_CORE_DEVKIT is not None:
        return FridaDevkitExt
    return FridaMissingDevkitBuildExt


if __name__ == "__main__":
    setup(
        name="frida",
        version=detect_version(),
        description="Dynamic instrumentation toolkit for developers, reverse-engineers, and security researchers",
        long_description=compute_long_description(),
        long_description_content_type="text/markdown",
        author="Frida Developers",
        author_email="oleavr@frida.re",
        url="https://frida.re",
        install_requires=["typing_extensions; python_version<'3.11'"],
        python_requires=">=3.7",
        license="wxWindows Library Licence, Version 3.1",
        keywords=(
            "frida debugger dynamic instrumentation inject javascript windows macos linux ios iphone ipad android qnx"
        ),
        classifiers=[
            "Development Status :: 5 - Production/Stable",
            "Environment :: Console",
            "Environment :: MacOS X",
            "Environment :: Win32 (MS Windows)",
            "Intended Audience :: Developers",
            "Intended Audience :: Science/Research",
            "License :: OSI Approved",
            "Natural Language :: English",
            "Operating System :: MacOS :: MacOS X",
            "Operating System :: Microsoft :: Windows",
            "Operating System :: POSIX :: Linux",
            "Programming Language :: Python :: 3",
            "Programming Language :: Python :: 3.7",
            "Programming Language :: Python :: 3.8",
            "Programming Language :: Python :: 3.9",
            "Programming Language :: Python :: 3.10",
            "Programming Language :: Python :: Implementation :: CPython",
            "Programming Language :: JavaScript",
            "Topic :: Software Development :: Debuggers",
            "Topic :: Software Development :: Libraries :: Python Modules",
        ],
        packages=["frida"],
        package_data={"frida": ["py.typed"]},
        ext_modules=[Extension(name="frida._frida", sources=[], py_limited_api=True)],
        cmdclass={"build_ext": select_build_ext(), "build_py": FridaGeneratedBuildPy},
        zip_safe=False,
    )
